# Generated by Django 4.2.3 on 2023-07-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('warranty_service', models.BooleanField(default=False, verbose_name='Centro tecnico autorizado?')),
                ('company', models.CharField(max_length=50, verbose_name='Compañía')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('occupation', models.CharField(max_length=50, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('document', models.CharField(max_length=20, verbose_name='Documento')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Celular')),
                ('second_phone_number', models.CharField(max_length=20, verbose_name='Telefono')),
                ('department', models.CharField(max_length=20, verbose_name='Departamento')),
                ('municipality', models.CharField(max_length=30, verbose_name='Municipio')),
                ('address', models.CharField(max_length=200, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, verbose_name='Referencia')),
                ('manpower', models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='Mano de obra')),
                ('exploded_view', models.FileField(upload_to='exploded_views', verbose_name='Despiece')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('is_guarantee', models.BooleanField(default=False)),
                ('service_number', models.CharField(max_length=30, null=True)),
                ('serial', models.CharField(max_length=30)),
                ('observations', models.TextField(max_length=500)),
                ('diagnostic', models.TextField(max_length=1000, null=True)),
                ('estimate_for_repair', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('payment', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('payment_for_revision', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('received', 'Recibido'), ('admitted', 'Ingresado'), ('in_revision', 'En revision'), ('revised', 'Revisado'), ('waiting_for_spare_parts', 'En espera de respuestos'), ('in_repair', 'En reparacion'), ('repaired', 'Listo para entregar'), ('delivered', 'Entregado')], default=('received', 'Recibido'), max_length=25)),
                ('brand_of_the_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.category')),
                ('checked_and_or_repaired_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisado_o_reparado_por', to='orders.collaborator')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibido_por', to='orders.collaborator')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.reference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidences', verbose_name='Imagen')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='orders.order', verbose_name='Orden')),
            ],
        ),
    ]
