# Generated by Django 4.2.3 on 2023-07-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.CharField(max_length=50, null=True, verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.category', verbose_name='Categoria'),
        ),
    ]
