# Generated by Django 4.2.3 on 2023-07-15 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_brand_company_alter_reference_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['reference'], 'verbose_name': 'Reference', 'verbose_name_plural': 'Referencies'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('electric_tools', 'Herramientas electricas'), ('cordless_tools', 'Herramientas inalámbricas'), ('combustion_machines', 'Maquinas de combustión'), ('welding', 'Soldadura'), ('home_appliances', 'Electrodomésticos'), ('white_line', 'Linea blanca'), ('agricultural_tools', 'Herramienta agrícola'), ('others', 'Otros')], default=('electric_tools', 'Herramientas electricas'), max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_refencies', to='orders.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_refencies', to='orders.category', verbose_name='Categoria'),
        ),
    ]
