# Generated by Django 4.2.3 on 2023-07-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_reference_options_alter_brand_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterField(
            model_name='reference',
            name='exploded_view',
            field=models.FileField(null=True, upload_to='exploded_views', verbose_name='Despiece'),
        ),
    ]
