# Generated by Django 4.2.3 on 2023-08-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_user_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='logos', verbose_name='Logo o imagen'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='email'),
        ),
    ]
