# Generated by Django 4.2.3 on 2023-08-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_brand_image_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefono'),
        ),
    ]
