# Generated by Django 4.2.3 on 2023-08-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_reason_for_damage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reason_for_damage',
            new_name='reason_for_entry',
        ),
    ]
