# Generated by Django 4.2.3 on 2023-08-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='brand_of_the_product',
            new_name='brand_id',
        ),
    ]
