# Generated by Django 4.2.3 on 2023-08-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_brand_id_order_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
