# Generated by Django 4.2.3 on 2023-08-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_user_client_rename_user_order_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaborator',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
