# Generated by Django 4.2.3 on 2023-08-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['fullname'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
    ]
