# Generated by Django 4.2.3 on 2023-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admitted_date',
            field=models.DateField(null=True, verbose_name='Fecha ingresado'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(null=True, verbose_name='Fecha entregado'),
        ),
        migrations.AddField(
            model_name='order',
            name='quoted_date',
            field=models.DateField(null=True, verbose_name='Fecha cotizado'),
        ),
        migrations.AddField(
            model_name='order',
            name='reapired_date',
            field=models.DateField(null=True, verbose_name='Fecha reparado'),
        ),
        migrations.AddField(
            model_name='order',
            name='revised_date',
            field=models.DateField(null=True, verbose_name='Fecha revisado'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_service',
            field=models.CharField(choices=[('collect', 'Cobro'), ('warranty', 'Garantia'), ('workshop_warranty', 'Garantia de taller'), ('warranty_denial', 'Negacion de garantia'), ('workshop_warranty_denial', 'Negacion de garantia de taller')], default=('collect', 'Cobro'), max_length=25),
        ),
        migrations.AddField(
            model_name='order',
            name='warranty_denial_date',
            field=models.DateField(null=True, verbose_name='Fecha negacion garantia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_date',
            field=models.DateTimeField(verbose_name='Fecha recibido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('received', 'Recibido'), ('admitted', 'Ingresado'), ('in_revision', 'En revision'), ('revised', 'Revisado'), ('waiting_response_brand', 'En espera de respuesta de la marca'), ('warranty_denial', 'Negacion de garantia'), ('quoted', 'Cotizado'), ('waiting_for_spare_parts', 'En espera de repuestos'), ('spare_parts_ready', 'Repuestos en taller'), ('in_repair', 'En reparacion'), ('repaired', 'Listo para entregar'), ('delivered', 'Entregado')], default=('received', 'Recibido'), max_length=25),
        ),
    ]
