# Generated by Django 3.2.12 on 2023-12-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_is_necesary_spare_parts_order_spare_parts_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='genre',
            field=models.CharField(max_length=20, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Order', to='orders.client'),
        ),
    ]
