# Generated by Django 3.2.12 on 2023-12-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20231229_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='genre',
            new_name='genred',
        ),
    ]
