# Generated by Django 3.2.12 on 2024-01-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_rename_genre_client_genred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='estimate_for_repair',
            new_name='price_estimate_for_repair',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_for_revision',
            new_name='price_for_revision',
        ),
    ]
