# Generated by Django 5.1.6 on 2025-03-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_rename_repared_by_order_repaired_by_and_more'),
    ]

    operations = [
    ]
